// Generated by CoffeeScript 1.3.3

module.exports = function(store) {
    
  store.query.expose('countries', 'getCountryList', function(keywords) {
        return this.where('keywords').contains(keywords).limit(5);
  });
    
};
